### ISSUE TITLE
Bug : Scientific notation

### ISSUE THREAD

**Issue by cath34** [axkr/symja_android_library#54]
# Submit a feature request or bug report

### Is this a request for a feature or a bug report?

Bug report 

### What is the current behavior?

When I evaluate this expression:
Simplify((2E-14) * x)
I get : 
-8.56343634308191*a

In the online demo, I get:
2 * (e-7) * x

### If this is a bug report, please provide steps to reproduce:
```
            ExprEvaluator util = new ExprEvaluator();
            String commandToExecute = "Simplify("+"(2E-14) * x"+")";
            IExpr input = util.eval(commandToExecute);
```
### What is the expected or desired behavior?  

Interpret E as (*10^)

### Please describe your development environment (OS, browser, etc.):

Windows

**Comment by axkr** [comment]
Use `Config.EXPLICIT_TIMES_OPERATOR=true` otherwise your expression is interpreted as `2*E-14*x`

```
			Config.EXPLICIT_TIMES_OPERATOR=true;
            ExprEvaluator util = new ExprEvaluator();
            String commandToExecute = "Simplify("+"(2E-14) * x"+")";
            IExpr input = util.eval(commandToExecute);
			System.out.println(input.toString()); Config.EXPLICIT_TIMES_OPERATOR=true;
            ExprEvaluator util = new ExprEvaluator();
            String commandToExecute = "Simplify("+"(2E-14) * x"+")";
            IExpr input = util.eval(commandToExecute);
			System.out.println(input.toString()); 
```

**Comment by axkr** [comment]
Here is an suggestion to mimic the Mathematica output format in the future.
See the [DoubleToMMAFormat#doubleToMMA()](https://gist.github.com/axkr/4e3e895505e75ed32a52128d1862a267) method.

May be an additional option in the future to avoid the standard Java double notation, because Symja use `E`  as a constant symbol for [Euler's constant](https://en.wikipedia.org/wiki/E_(mathematical_constant)).
