### ISSUE TITLE
Implement GRPC Symja Client/Server

### ISSUE THREAD

**Issue by axkr** [axkr/symja_android_library#96]
In this project [gRPC Symja example project](https://github.com/axkr/symja-grpc-java) it's sketched how a Symja serialization could be created on top of [gRPC](https://grpc.io/) (see this video: [gRPC 101 for Java Developers by Ray Tsang](https://www.youtube.com/watch?v=DU-q5kOf2Rc) )

Use this as a basis to integrate 
* a server component into Symja in package `org.matheclipse.core.eval`
* change the arguments in `MMAConsole` and `Console` in package `org.matheclipse.core.eval`, so that they can use a started server for evaluating the user input strings.
* in the first step gRPC serialization and deserialization will not work between different versions

**Comment by corywalker** [comment]
Hi Axel,

I took a look at the example project a week ago and I found it was a bit too Symja specific for me to share to code:

1. I think the main thing is that there is a concept of a built in Symbol assigned to an ID. Any other services will not have the same mapping as you and will thus need to build a lookup table instead of just putting in the symbol name.
2. There are many references to matheclipse/symja.
3. I'm not sure why patterns get their own Atom.
4. The use of the "double" proto type makes it impossible to use big double numbers. Perhaps we should use a string type here?

If we can make a decision on some of these points, I'm happy to help with the changes on both the Symja side and also to build a compatible client from the Expreduce side.

**Comment by axkr** [comment]
OK, can you add your Suggestion of the proto format you have in mind to this issue so we can discuss it further.

**Comment by axkr** [comment]
Internally I've implemented patterns as Atoms, but for grpc i can also generate them from their FullForm. Same is true for Rational and Complex objects.

**Comment by axkr** [comment]
BinarySerialize, BinaryDeserialize move to new issue #98

**Comment by axkr** [comment]
Closed for now. Reopen if necessary
